global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "platforms-web"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - web-container:5050

  - job_name: windows
    static_configs:
      - targets:
          - host.docker.internal:9182
        labels:
          host: windows-host
          os: windows
          lab: desktoplab
          role: desktop