# Use Official Python Image
FROM python:3.10-slim

# Set working directory
WORKDIR /app
# Copy app files
COPY . /app
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Expose port for Flask
EXPOSE 5050
# Run the app
CMD ["python", "app.py"]
