name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt
      - name: Lint the app
        run: |
          pip install flake8
          flake8 app/app.py
      - name: Run the app
        run: |
          echo "Running the app..."
          python3 -c "import app"